apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: extension-shoot-agent-sandbox
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/shoot-agent-sandbox:v0.1.0-dev
  resources:
  - kind: Extension
    type: shoot-agent-sandbox
