//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	operator "github.com/gardener/gardener-extension-shoot-agent-sandbox/pkg/apis/operator"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AgentSandbox)(nil), (*operator.AgentSandbox)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AgentSandbox_To_operator_AgentSandbox(a.(*AgentSandbox), b.(*operator.AgentSandbox), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*operator.AgentSandbox)(nil), (*AgentSandbox)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_operator_AgentSandbox_To_v1alpha1_AgentSandbox(a.(*operator.AgentSandbox), b.(*AgentSandbox), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Extensions)(nil), (*operator.Extensions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Extensions_To_operator_Extensions(a.(*Extensions), b.(*operator.Extensions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*operator.Extensions)(nil), (*Extensions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_operator_Extensions_To_v1alpha1_Extensions(a.(*operator.Extensions), b.(*Extensions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AgentSandbox_To_operator_AgentSandbox(in *AgentSandbox, out *operator.AgentSandbox, s conversion.Scope) error {
	out.Extensions = (*operator.Extensions)(unsafe.Pointer(in.Extensions))
	return nil
}

// Convert_v1alpha1_AgentSandbox_To_operator_AgentSandbox is an autogenerated conversion function.
func Convert_v1alpha1_AgentSandbox_To_operator_AgentSandbox(in *AgentSandbox, out *operator.AgentSandbox, s conversion.Scope) error {
	return autoConvert_v1alpha1_AgentSandbox_To_operator_AgentSandbox(in, out, s)
}

func autoConvert_operator_AgentSandbox_To_v1alpha1_AgentSandbox(in *operator.AgentSandbox, out *AgentSandbox, s conversion.Scope) error {
	out.Extensions = (*Extensions)(unsafe.Pointer(in.Extensions))
	return nil
}

// Convert_operator_AgentSandbox_To_v1alpha1_AgentSandbox is an autogenerated conversion function.
func Convert_operator_AgentSandbox_To_v1alpha1_AgentSandbox(in *operator.AgentSandbox, out *AgentSandbox, s conversion.Scope) error {
	return autoConvert_operator_AgentSandbox_To_v1alpha1_AgentSandbox(in, out, s)
}

func autoConvert_v1alpha1_Extensions_To_operator_Extensions(in *Extensions, out *operator.Extensions, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha1_Extensions_To_operator_Extensions is an autogenerated conversion function.
func Convert_v1alpha1_Extensions_To_operator_Extensions(in *Extensions, out *operator.Extensions, s conversion.Scope) error {
	return autoConvert_v1alpha1_Extensions_To_operator_Extensions(in, out, s)
}

func autoConvert_operator_Extensions_To_v1alpha1_Extensions(in *operator.Extensions, out *Extensions, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_operator_Extensions_To_v1alpha1_Extensions is an autogenerated conversion function.
func Convert_operator_Extensions_To_v1alpha1_Extensions(in *operator.Extensions, out *Extensions, s conversion.Scope) error {
	return autoConvert_operator_Extensions_To_v1alpha1_Extensions(in, out, s)
}
