---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-sandbox.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "agent-sandbox.name" . }}
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  type: ClusterIP
  selector:
    app: {{ include "agent-sandbox.name" . }}
  ports:
  - name: metrics
    port: {{ .Values.service.ports.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.metrics.targetPort }}
  - name: webhook-server
    port: {{ .Values.service.ports.webhookServer.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.webhookServer.targetPort }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "agent-sandbox.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "agent-sandbox.name" . }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ include "agent-sandbox.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "agent-sandbox.name" . }}
    spec:
      automountServiceAccountToken: false
{{/*      serviceAccountName: {{ include "agent-sandbox.name" . }}*/}}
      containers:
      - name: {{ include "agent-sandbox.name" . }}
        image: {{ index .Values.images "agent-sandbox" }}
        imagePullPolicy: {{ .Values.controller.pullPolicy }}
---